apiVersion: v1
kind: Namespace
metadata:
  name: ci-jenkins

---

apiVersion: v1
kind: Namespace
metadata:
  name: observation

---

apiVersion: v1
kind: Namespace
metadata:
  name: mongodb

---

apiVersion: v1
kind: Namespace
metadata:
  name: argocd




