# deployment.yaml for My App

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matan-app # Use a static name for debugging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matan-app
  template:
    metadata:
      labels:
        app: matan-app
    spec:
      containers:
        - name: matan-app
          image: matanzh/web-app:latest  # Updated image to matanzh/web-app:latest
          ports:
            - containerPort: 5000
